version: '3.8'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/db
      NODE_ENV: development
      PORT: 3000
      REDIS: 6379
    ports:
      - '3000:3000'

  postgres:
    image: postgres:10.4
    ports:
      - '35000:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    restart: always
